### 转录功能
POST  http://localhost:3000/api/v1/tingwu/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Q5YTZiMy01N2Y5LTQyN2UtODUxMC02MTI4ODQ2OWJlOWIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYzMzg3MDUsImV4cCI6MTc0NjQyNTEwNX0.gjQUUkiCBC6aHHJS9es1F3zebbbmAtZWXiKtSq_iY9g

{
    "type": "offline",
    "input": {
        "sourceLanguage": "cn",
        "fileUrl": "https://focus-01.oss-cn-beijing.aliyuncs.com/audio/20250413T123935-1355d577-b11e-4d49-84bd-a5f73dccb7a8-4%C3%A6%C2%9C%C2%884%C3%A6%C2%97%C2%A5.MP3"
    },
    "parameters": {
        "translationEnabled": false,
        "translation": {
            "targetLanguages": ["en"],
            "outputLevel": 2
        },
        "transcoding": {
            "targetAudioFormat": "mp3"
        },
        "transcription": {
            "audioEventDetectionEnabled": true,
            "diarization": { 
                "speakerCount": 2
            },
            "outputLevel": 2
        },
        "autoChaptersEnabled": false,
        "meetingAssistanceEnabled": false,
        "meetingAssistance": {
            "types": ["Actions", "KeyInformation"]
        },
        "summarizationEnabled": false,
        "summarization": {
            "types": ["Paragraph", "Conversational", "QuestionsAnswering"]
        }
    }
}

# type = offline Response
# {
#   "success": true,
#   "message": "成功创建通义听悟任务",
#   "data": {
#     "taskId": "6e4b5a1de3184ca298755eb3821a7225",
#     "taskStatus": "ONGOING",
#     "requestId": "5D5368CE-93CA-5761-B71D-3A57AA1FDB6D"
#   },
#   "timestamp": "2025-05-03T07:46:11.287Z"
# }

# {
#   "success": true,
#   "message": "成功创建通义听悟任务",
#   "data": {
#     "taskId": "6e4b5a1de3184ca298755eb3821a7225",
#     "taskStatus": "ONGOING",
#     "requestId": "5D5368CE-93CA-5761-B71D-3A57AA1FDB6D"
#   },
#   "timestamp": "2025-05-03T07:46:11.287Z"
# }

# type = realtime Response
# {
#   "success": true,
#   "message": "成功创建通义听悟任务",
#   "data": {
#     "taskId": "63510af9846844f0a7d6ebe246e4059d",
#     "taskStatus": "NEW",
#     "requestId": "67E457F2-A06A-5FFC-8858-4FB0256C7F9A",
#     "meetingJoinUrl": "wss://tingwu-realtime-cn-beijing.aliyuncs.com/api/ws/v1?mc=6FloKJ2A5FpvudAL8NcU40Wj4PYPFHSqSh6UWmx8S2Ttv-5lvS-v9OqePlMENkIdGO1QMqOCTTbvymC6QX2f0OHjZeb92l38a_DhBCCahWfgWaYk2IfgFxg2uMosOhdV"
#   },
#   "timestamp": "2025-05-03T12:27:28.510Z"
# }



###
GET http://localhost:3000/api/v1/tingwu/tasks/c56cc7049a3d41dd9dbf5965e8d7beb6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Q5YTZiMy01N2Y5LTQyN2UtODUxMC02MTI4ODQ2OWJlOWIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYzMzg3MDUsImV4cCI6MTc0NjQyNTEwNX0.gjQUUkiCBC6aHHJS9es1F3zebbbmAtZWXiKtSq_iY9g

# {
#   "success": true,
#   "message": "成功获取通义听悟任务信息",
#   "data": {
#     "code": "0",
#     "data": {
#       "result": {
#         "autoChapters": "https://prod-tingwu-paas-common-beijing.oss-cn-beijing.aliyuncs.com/tingwu/output/1767782021063526/ed002fc205464995a7dc1f7aee3bb7eb/ed002fc205464995a7dc1f7aee3bb7eb_AutoChapters_20250503144225.json?Expires=1748846549&OSSAccessKeyId=LTAI5tMzZ1D4o1drkJN1TfCr&Signature=D1YpshUluVjg1v19qauDIdXtnTg%3D",
#         "transcription": "https://prod-tingwu-paas-common-beijing.oss-cn-beijing.aliyuncs.com/tingwu/output/1767782021063526/ed002fc205464995a7dc1f7aee3bb7eb/ed002fc205464995a7dc1f7aee3bb7eb_Transcription_20250503144210.json?Expires=1748846549&OSSAccessKeyId=LTAI5tMzZ1D4o1drkJN1TfCr&Signature=GxzEVk7Jl0jyuwEff5QfZu%2B0rwg%3D"
#       },
#       "taskId": "ed002fc205464995a7dc1f7aee3bb7eb",
#       "taskStatus": "COMPLETED"
#     },
#     "message": "success",
#     "requestId": "2D0D4535-6E9B-5AD1-91F5-67B491094E7F"
#   },
#   "timestamp": "2025-05-03T06:42:29.603Z"
# }

# {
#   "success": true,
#   "message": "成功获取通义听悟任务信息",
#   "data": {
#     "taskId": "6e4b5a1de3184ca298755eb3821a7225",
#     "taskStatus": "COMPLETED",
#     "requestId": "092D775C-FF50-590C-BAD7-E7ADB320739E",
#     "result": {
#       "transcription": "https://prod-tingwu-paas-common-beijing.oss-cn-beijing.aliyuncs.com/tingwu/output/1767782021063526/6e4b5a1de3184ca298755eb3821a7225/6e4b5a1de3184ca298755eb3821a7225_Transcription_20250503154620.json?Expires=1748850418&OSSAccessKeyId=LTAI5tMzZ1D4o1drkJN1TfCr&Signature=KjM3MY25FPKKnbQuscK3XJrjXoE%3D",
#       "translation": "https://prod-tingwu-paas-common-beijing.oss-cn-beijing.aliyuncs.com/tingwu/output/1767782021063526/6e4b5a1de3184ca298755eb3821a7225/6e4b5a1de3184ca298755eb3821a7225_Translation_20250503154621.json?Expires=1748850418&OSSAccessKeyId=LTAI5tMzZ1D4o1drkJN1TfCr&Signature=%2FWAVQzLBJlLbM9i0yti03S3uA%2F4%3D"
#     }
#   },
#   "timestamp": "2025-05-03T07:46:58.763Z"
# }



