### 保存翻译记录
POST  http://localhost:3000/api/v1/translation/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Q5YTZiMy01N2Y5LTQyN2UtODUxMC02MTI4ODQ2OWJlOWIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYzMzg3MDUsImV4cCI6MTc0NjQyNTEwNX0.gjQUUkiCBC6aHHJS9es1F3zebbbmAtZWXiKtSq_iY9g

{
    "taskId": "e224ad57504e42109a192165740fb6e2",
    "title": "同传翻译 2025/5/4 23:10:55",
    "sourceLanguage": "cn",
    "targetLanguage": "en",
    "originalText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。",
    "translatedText": "No, right, right? But not now. Now Guiyang is starting to engage in cloud computing, big data and intelligent network connection. What will happen when the industry gets angry? Local people earn\nThe local people have made money, you",
    "duration": 9,
    "timestamp": 1746371455967,
    "outputMp3Path": "https://example.com/audio/sample-mp3-file.mp3",
    "taskStatus": "COMPLETED"
}


# 保存翻译记录 Response
# {
#   "success": true,
#   "message": "翻译记录保存成功",
#   "data": {
#     "id": "0bd197dd-2e6f-4b15-9f60-cb2f5ec62e58",
#     "sourceText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。",
#     "translatedText": "No, right, right? But not now. Now Guiyang is starting to engage in cloud computing, big data and intelligent network connection. What will happen when the industry gets angry? Local people earn\nThe local people have made money, you",
#     "sourceLanguage": "cn",
#     "targetLanguage": "en",
#     "isFavorite": false,
#     "isVoice": false,
#     "createdAt": "2025-05-04T15:23:29.278Z",
#     "userId": "17d9a6b3-57f9-427e-8510-61288469be9b",
#     "duration": 9,
#     "errorMessage": null,
#     "outputMp3Path": "https://example.com/audio/sample-mp3-file.mp3",
#     "status": "COMPLETED",
#     "tags": [],
#     "taskId": "e224ad57504e42109a192165740fb6e2",
#     "taskStatus": "COMPLETED",
#     "timestamp": 1746371455967,
#     "title": "同传翻译 2025/5/4 23:10:55",
#     "updatedAt": "2025-05-04T15:23:29.278Z",
#     "originalText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。"
#   },
#   "timestamp": "2025-05-04T15:23:29.290Z"
# }


### 获取翻译记录列表
GET  http://localhost:3000/api/v1/translation/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Q5YTZiMy01N2Y5LTQyN2UtODUxMC02MTI4ODQ2OWJlOWIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYzMzg3MDUsImV4cCI6MTc0NjQyNTEwNX0.gjQUUkiCBC6aHHJS9es1F3zebbbmAtZWXiKtSq_iY9g

# 获取翻译记录列表 Response
# {
#   "success": true,
#   "message": "获取翻译记录列表成功",
#   "data": {
#     "total": 1,
#     "list": [
#       {
#         "id": "c572993e-098f-4874-8230-24d8ef2349a4",
#         "sourceText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。",
#         "translatedText": "No, right, right? But not now. Now Guiyang is starting to engage in cloud computing, big data and intelligent network connection. What will happen when the industry gets angry? Local people earn\nThe local people have made money, you",
#         "sourceLanguage": "cn",
#         "targetLanguage": "en",
#         "isFavorite": false,
#         "isVoice": false,
#         "createdAt": "2025-05-04T15:19:15.996Z",
#         "userId": "17d9a6b3-57f9-427e-8510-61288469be9b",
#         "duration": 9,
#         "errorMessage": null,
#         "outputMp3Path": "https://example.com/audio/sample-mp3-file.mp3",
#         "status": "COMPLETED",
#         "tags": [],
#         "taskId": "e224ad57504e42109a192165740fb6e2",
#         "taskStatus": "COMPLETED",
#         "timestamp": 1746371455967,
#         "title": "同传翻译 2025/5/4 23:10:55",
#         "updatedAt": "2025-05-04T15:19:15.996Z",
#         "originalText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。"
#       }
#     ]
#   },
#   "timestamp": "2025-05-04T15:22:37.186Z"
# }

### 获取翻译记录详情
GET  http://localhost:3000/api/v1/translation/detail/c572993e-098f-4874-8230-24d8ef2349a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Q5YTZiMy01N2Y5LTQyN2UtODUxMC02MTI4ODQ2OWJlOWIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYzMzg3MDUsImV4cCI6MTc0NjQyNTEwNX0.gjQUUkiCBC6aHHJS9es1F3zebbbmAtZWXiKtSq_iY9g

# 翻译记录详情 Response
# {
#   "success": true,
#   "message": "获取翻译记录详情成功",
#   "data": {
#     "id": "c572993e-098f-4874-8230-24d8ef2349a4",
#     "sourceText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。",
#     "translatedText": "No, right, right? But not now. Now Guiyang is starting to engage in cloud computing, big data and intelligent network connection. What will happen when the industry gets angry? Local people earn\nThe local people have made money, you",
#     "sourceLanguage": "cn",
#     "targetLanguage": "en",
#     "isFavorite": false,
#     "isVoice": false,
#     "createdAt": "2025-05-04T15:19:15.996Z",
#     "userId": "17d9a6b3-57f9-427e-8510-61288469be9b",
#     "duration": 9,
#     "errorMessage": null,
#     "outputMp3Path": "https://example.com/audio/sample-mp3-file.mp3",
#     "status": "COMPLETED",
#     "tags": [],
#     "taskId": "e224ad57504e42109a192165740fb6e2",
#     "taskStatus": "COMPLETED",
#     "timestamp": 1746371455967,
#     "title": "同传翻译 2025/5/4 23:10:55",
#     "updatedAt": "2025-05-04T15:19:15.996Z",
#     "originalText": "没有，没错，对吧？但是现在不是的，现在贵阳开始搞云计算，开始搞大数据，搞智能网联。那产业一生气会有什么后果呢？当地的人挣到钱了，你。"
#   },
#   "timestamp": "2025-05-04T15:23:02.572Z"
# }

### 删除翻译记录
DELETE  http://localhost:3000/api/v1/translation/delete/c572993e-098f-4874-8230-24d8ef2349a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Q5YTZiMy01N2Y5LTQyN2UtODUxMC02MTI4ODQ2OWJlOWIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYzMzg3MDUsImV4cCI6MTc0NjQyNTEwNX0.gjQUUkiCBC6aHHJS9es1F3zebbbmAtZWXiKtSq_iY9g

# 删除翻译记录 Response
# {
#   "success": true,
#   "message": "删除翻译记录成功",
#   "data": {
#     "success": true
#   },
#   "timestamp": "2025-05-04T15:24:36.098Z"
# }





